# Generated by Django 3.2.4 on 2022-06-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='professor_details',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_fname', models.CharField(max_length=25)),
                ('p_lname', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('q_v', models.IntegerField()),
                ('q_a', models.IntegerField()),
                ('a_v', models.IntegerField()),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('s_fname', models.CharField(max_length=25)),
                ('s_lname', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('q_p', models.IntegerField()),
                ('q_a', models.IntegerField()),
                ('r_no', models.CharField(max_length=8)),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='visters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('q_text', models.CharField(max_length=500)),
                ('domain', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='ques_pbna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.question')),
            ],
        ),
        migrations.CreateModel(
            name='nof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField()),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.question')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='lib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.question')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('a_text', models.CharField(max_length=250)),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.question')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student_details')),
            ],
        ),
    ]
