# Generated by Django 3.2.4 on 2022-06-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('s_time', models.DateField()),
                ('a_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.answer')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.professor_details')),
                ('q_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.question')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='question_verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=5)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.professor_details')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.question')),
            ],
        ),
        migrations.CreateModel(
            name='question_jpg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.CharField(max_length=250)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.question')),
            ],
        ),
        migrations.CreateModel(
            name='answer_verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=5)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.answer')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.professor_details')),
            ],
        ),
        migrations.CreateModel(
            name='answer_jpg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.CharField(max_length=250)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.answer')),
            ],
        ),
    ]
